// flow-typed signature: d878d7008154208971f734c1087d2af5
// flow-typed version: <<STUB>>/react-native_v0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native' {
  declare module.exports: any;
}
